/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as PlayPracticeRouteImport } from './routes/play/practice'
import { Route as PlayOnlineRouteImport } from './routes/play/online'
import { Route as PlayLocalRouteImport } from './routes/play/local'
import { Route as PlayFriendRouteImport } from './routes/play/friend'
import { Route as PlayBotsRouteImport } from './routes/play/bots'
import { Route as ApiMultiplayerRoomRouteImport } from './routes/api/multiplayer/room'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAblyTokenRouteImport } from './routes/api/ably/token'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPracticeRoute = PlayPracticeRouteImport.update({
  id: '/play/practice',
  path: '/play/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOnlineRoute = PlayOnlineRouteImport.update({
  id: '/play/online',
  path: '/play/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/play/local',
  path: '/play/local',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFriendRoute = PlayFriendRouteImport.update({
  id: '/play/friend',
  path: '/play/friend',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBotsRoute = PlayBotsRouteImport.update({
  id: '/play/bots',
  path: '/play/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMultiplayerRoomRoute = ApiMultiplayerRoomRouteImport.update({
  id: '/api/multiplayer/room',
  path: '/api/multiplayer/room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAblyTokenRoute = ApiAblyTokenRouteImport.update({
  id: '/api/ably/token',
  path: '/api/ably/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/play/bots': typeof PlayBotsRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/practice': typeof PlayPracticeRoute
  '/play/': typeof PlayIndexRoute
  '/api/ably/token': typeof ApiAblyTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/multiplayer/room': typeof ApiMultiplayerRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/play/bots': typeof PlayBotsRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/practice': typeof PlayPracticeRoute
  '/play': typeof PlayIndexRoute
  '/api/ably/token': typeof ApiAblyTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/multiplayer/room': typeof ApiMultiplayerRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/play/bots': typeof PlayBotsRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/local': typeof PlayLocalRoute
  '/play/online': typeof PlayOnlineRoute
  '/play/practice': typeof PlayPracticeRoute
  '/play/': typeof PlayIndexRoute
  '/api/ably/token': typeof ApiAblyTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/multiplayer/room': typeof ApiMultiplayerRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/play/bots'
    | '/play/friend'
    | '/play/local'
    | '/play/online'
    | '/play/practice'
    | '/play/'
    | '/api/ably/token'
    | '/api/auth/$'
    | '/api/multiplayer/room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/play/bots'
    | '/play/friend'
    | '/play/local'
    | '/play/online'
    | '/play/practice'
    | '/play'
    | '/api/ably/token'
    | '/api/auth/$'
    | '/api/multiplayer/room'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/play/bots'
    | '/play/friend'
    | '/play/local'
    | '/play/online'
    | '/play/practice'
    | '/play/'
    | '/api/ably/token'
    | '/api/auth/$'
    | '/api/multiplayer/room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  PlayBotsRoute: typeof PlayBotsRoute
  PlayFriendRoute: typeof PlayFriendRoute
  PlayLocalRoute: typeof PlayLocalRoute
  PlayOnlineRoute: typeof PlayOnlineRoute
  PlayPracticeRoute: typeof PlayPracticeRoute
  PlayIndexRoute: typeof PlayIndexRoute
  ApiAblyTokenRoute: typeof ApiAblyTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMultiplayerRoomRoute: typeof ApiMultiplayerRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/practice': {
      id: '/play/practice'
      path: '/play/practice'
      fullPath: '/play/practice'
      preLoaderRoute: typeof PlayPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/online': {
      id: '/play/online'
      path: '/play/online'
      fullPath: '/play/online'
      preLoaderRoute: typeof PlayOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/local': {
      id: '/play/local'
      path: '/play/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/friend': {
      id: '/play/friend'
      path: '/play/friend'
      fullPath: '/play/friend'
      preLoaderRoute: typeof PlayFriendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/bots': {
      id: '/play/bots'
      path: '/play/bots'
      fullPath: '/play/bots'
      preLoaderRoute: typeof PlayBotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/multiplayer/room': {
      id: '/api/multiplayer/room'
      path: '/api/multiplayer/room'
      fullPath: '/api/multiplayer/room'
      preLoaderRoute: typeof ApiMultiplayerRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ably/token': {
      id: '/api/ably/token'
      path: '/api/ably/token'
      fullPath: '/api/ably/token'
      preLoaderRoute: typeof ApiAblyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  PlayBotsRoute: PlayBotsRoute,
  PlayFriendRoute: PlayFriendRoute,
  PlayLocalRoute: PlayLocalRoute,
  PlayOnlineRoute: PlayOnlineRoute,
  PlayPracticeRoute: PlayPracticeRoute,
  PlayIndexRoute: PlayIndexRoute,
  ApiAblyTokenRoute: ApiAblyTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMultiplayerRoomRoute: ApiMultiplayerRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
